{% set name = "libcxxwrap-julia" %}
{% set version = "0.3.0" %}
{% set sha256 = "b045a251207b99d765328c587cbbde6a246c82e4034958e3a89abcbbdc2271e2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaInterop/libcxxwrap-julia/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Julia has not been packaged for conda on OS X or Windows
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - julia >=0.6,<0.7
  run:
    - julia >=0.6,<0.7

test:
  commands:
    - test -d ${PREFIX}/include/jlcxx  # [unix]
    - test -f ${PREFIX}/include/jlcxx/jlcxx.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/JlCxx/JlCxxConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/JlCxx/JlCxxConfigVersion.cmake  # [unix]

    - if exist %LIBRARY_PREFIX%\include\JlCxx\jlcxx.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\JlCxx\JlCxxConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\JlCxx\JlCxxConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/JuliaInterop/CxxWrap.jl
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Seamless operability between C++11 and Julia'
  description: 'Lightweight library that exposes C++ types in Julia and vice versa'
  doc_url: https://github.com/JuliaInterop/libcxxwrap-julia
  dev_url: https://github.com/JuliaInterop/libcxxwrap-julia

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - barche
