travis:
  secure:
    BINSTAR_TOKEN: XGT9fKgx3aEDjO+YR/Xfr+bWPwHs6GNPHsgM9sfs28rgZPEek2Jub1F7sGzR7gWW10ZTq32wTEW98TyR1MadoPy4e8Oksv5EBnX8MTDkyNTVUuTMTwuuF5Ong/Bxex1sQ8vGgpoiK/opIPSrRII/z3YApBlRtmt83AKfEe5HKFsmG5K8rDud33FriVJ2BxptbHiLLf67aDj/FVy+7dCRuA/wgXZEsFuG03WqZK/J9Is/Yj2JgsL2jZKesjmAGMy8dJxtoUOc/0QTwTk1lrNxm9tCa2LK5Ul6SrOb3Wwz/+4zB4DWVR+QRQ4T8ZdWAjuHjHkWoWxWKcJamcw/ENUD6jT+Bro58e3zW2R2Fldqq0IE8GIvGUxCi20+MEgvyHlti/MmNXrkp7zUV+N1EGC0QAk87ZmpwwPVQa24TPVLJadBAlCsR/sLdlkNEskLgSVE3hA4gKlB/tJvtlhkkVlYX7zdxCAGJA5tGCiTcWQ5lVUZ7S88f3TOqXuBGKoJFY1YhbRCXQ7LcGlAHrPwmO7kgn/4E32pdfcx0OHbPR8IsIDNj0u8h8m5I8dg/9pjFL+uZRMUUIMc0IjVSF3Jg9GkEShXh3fh94UGpkOvtUoZ0NUci8kNDlQQTIeukjpce1/tpJ1na0qkxfYkQSmaBO1IbFf7f8Vx3haQwIJ4mS2Ebrs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
